sudo: required
dist: bionic
language: C++

matrix:

  include:

  - env:
    - PG=9.3
    - PGIS=2.4
  - env:
    - PG=9.4
    - PGIS=2.4
  - env:
    - PG=9.5
    - PGIS=2.4
  - env:
    - PG=9.6
    - PGIS=2.4
  - env:
    - PG=10
    - PGIS=2.4
  - env:
    - PG=11
    - PGIS=2.5

before_install:
  # Purge PostgreSQL packages
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5
    postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  # Enable fetching packages from packagecloud
  # test and production repositories
  - curl -s https://packagecloud.io/install/repositories/linz/test/script.deb.sh | sudo bash
  - curl -s https://packagecloud.io/install/repositories/linz/prod/script.deb.sh | sudo bash
  # Install packages
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends
    pgtap
    debhelper fakeroot
    postgresql-${PG}
    postgresql-server-dev-${PG}
    postgresql-contrib-${PG}
    postgresql-${PG}-pgtap
    postgresql-${PG}-postgis-${PGIS}
    postgresql-${PG}-postgis-${PGIS}-scripts
    postgresql-${PG}-tableversion
    postgresql-${PG}-dbpatch
    linz-bde-schema
    linz-bde-uploader

before_script:
  # Set PATH as in presence of multiple PostgreSQL packages
  # we may otherwise target the wrong one
  - export PATH=/usr/lib/postgresql/${PG}/bin:${PATH}
  # Set PGPORT as in presence of multiple running PostgreSQL packages
  # we may otherwise target the wrong one
  - export PGPORT=`pg_lsclusters ${PG} | grep online | awk '{print $3}'`
  - sudo -u postgres createuser -s "$USER"
  - sudo -u postgres createuser -s root

script:
  # Set PATH as in presence of multiple PostgreSQL packages
  # we may otherwise target the wrong one
  - export PATH=/usr/lib/postgresql/${PG}/bin:${PATH}
  - make
  - make check || { cat regression.diffs; false; }
  - sudo env "PATH=$PATH" env "PGPORT=$PGPORT" make install
  - make installcheck
  # stdout support requires:
  #   - dbpatch-1.4.0
  #   - linz-bde-uploader-2.5.0
  - make installcheck-stdout
  # Build docs
  ## Install docs generation dependencies
  - sudo apt-get install -y wkhtmltopdf xvfb
  - wget https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.1.1-1-amd64.deb
  ## Build the docs
  - xvfb-run make docs
  ## TODO: check docs quality ?
  # Test build and installation of debian package
  - make deb
  - sudo dpkg -i ../linz-lds-bde-schema*.deb
