sudo: required
language: C++

matrix:

  include:

  - env: PG=9.3/2.3
    addons:
      postgresql: 9.3
      apt:
        packages:
        - postgresql-9.3
        - postgresql-9.3-pgtap
        - postgresql-server-dev-9.3
        - postgresql-9.3-postgis-2.3
        - pgxnclient

  - env: PG=9.4/2.3
    addons:
      postgresql: 9.4
      apt:
        packages:
        - postgresql-9.4
        - postgresql-9.4-pgtap
        - postgresql-server-dev-9.4
        - postgresql-9.4-postgis-2.3

  - env: PG=9.5/2.3
    addons:
      postgresql: 9.5
      apt:
        packages:
        - postgresql-9.5
        - postgresql-9.5-pgtap
        - postgresql-server-dev-9.5
        - postgresql-9.5-postgis-2.3

  - env: PG=9.6/2.3
    addons:
      postgresql: 9.6
      apt:
        packages:
        - postgresql-9.6
        - postgresql-9.6-pgtap
        - postgresql-server-dev-9.6
        - postgresql-9.6-postgis-2.3

before_install:
  # Install common packages
  - sudo apt-get -qq update
  - sudo apt-get install -y pgtap pgxnclient wkhtmltopdf
  # Install pandoc
  - wget https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.1.1-1-amd64.deb
  # Check pgxnclient version
  - pgxn --version
  # Install dbpatch
  - wget https://github.com/linz/postgresql-dbpatch/archive/1.2.0.tar.gz
  - tar xzf 1.2.0.tar.gz
  - cd postgresql-dbpatch-1.2.0
  - make
  - sudo env "PATH=$PATH" make install
  - cd .. && rm -f 1.2.0.tar.gz
  # Install linz-bde-schema
  - wget https://github.com/linz/linz-bde-schema/archive/master.tar.gz
  - tar xzf master.tar.gz && cd linz-bde-schema-master
  - make
  - sudo env "PATH=$PATH" make install
  - cd .. && rm -f master.tar.gz
  # Install postgresql-tableversion
  - sudo env "PATH=$PATH" pgxn install
    https://github.com/linz/postgresql-tableversion/archive/1.4.0.tar.gz
  # Install linz-bde-uploader
  - wget https://github.com/linz/linz_bde_uploader/archive/2.4.0.tar.gz
  - tar xzf 2.4.0.tar.gz && cd linz_bde_uploader-2.4.0
  - ./configure && make
  - sudo env "PATH=$PATH" make install
  - cd .. && rm -rf 2.4.0.tar.gz linz_bde_uploader-2.4.0
script:
  - make
  - make check || { cat regression.diffs; false; }
  - sudo env "PATH=$PATH" make install
  - make installcheck
