#!/bin/sh

DB_NAME=
export SKIP_INDEXES=no
export EXTENSION_MODE=on
export PSQL=psql
export SCRIPTSDIR=/usr/share/linz-lds-bde-schema/sql/

if test -n "${LDSBDESCHEMA_SQLDIR}"; then
    SCRIPTSDIR=${LDSBDESCHEMA_SQLDIR}
fi

if test ! -f "${SCRIPTSDIR}/01-lds_layer_tables.sql"; then
    cat >&2 <<EOF
Cannot find 01-lds_layer_tables.sql in ${SCRIPTSDIR}
Please set LDSBDESCHEMA_SQLDIR environment variable
EOF
    exit 1
fi

while test -n "$1"; do
    if test $1 = "--noindexes"; then
        SKIP_INDEXES=yes
        shift; continue
    elif test $1 = "--noextension"; then
        EXTENSION_MODE=off
        shift; continue
    else
        DB_NAME=$1; shift
    fi
done

if test -z "$DB_NAME"; then
    echo "Usage: $0 [--revision] [--noextension] <database>" >&2
    exit 1
fi

# Enable table_version fi needed
if test "${ADD_REVISIONS}" = "yes"; then
    LOADER=`pg_config --bindir`/table_version-loader
    OPTS=
    if test "${EXTENSION_MODE}" = "off"; then
        OPTS="--no-extension"
    fi
    ${LOADER} ${OPTS} $PGDATABASE || exit 1
fi

export PGDATABASE=$DB_NAME
(
cat << EOF
CREATE EXTENSION IF NOT EXISTS unaccent;
EOF

for file in ${SCRIPTSDIR}/*.sql; do
    cat ${file}
done

if test "${ADD_REVISIONS}" = "yes"; then
    file=${SCRIPTSDIR}/versioning/01-version_tables.sql
    cat ${file} || exit 1
fi

) | $PSQL -tA --set ON_ERROR_STOP=1
